// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zgyucnpsbcklkydsdjyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpneXVjbnBzYmNrbGt5ZHNkanlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NzA2MjQsImV4cCI6MjA3NDU0NjYyNH0.FgaB-aONpJSnBVr9mGZVe81OGniYJnYMWJ14GZps-fE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});